### PR TITLE
docs: update readme file

### LINKED ISSUE #135: docs: update readme file
The readme file has to be updated. The contribution guidelines have moved to a new file. It has to be removed and new additions like app screenshots etc has to be added. Make the readme look attractive. Also add vercel, livekit and appwrite logo.

### PR DESCRIPTION
**Pull request by ShivamMenda**
Closes #135

### CODE REVIEW

**Comment by ShivamMenda** [comment]
@chandansgowda Added the logos and links to make the readme look better. Only App screenshots are remaining. Which screens do you want me to include?

**Comment by chandansgowda** [comment]
Include all screens

**Comment by chandansgowda** [comment]
Also please look into readme files of popular open source projects and format it nicely.

**Comment by ShivamMenda** [comment]
> Also please look into readme files of popular open source projects and format it nicely.

@chandansgowda yes I took reference of projects that have been sponsored before. Followed the vercel guidelines and this year appwrite has closed their oss funding but we can apply in Jan. we can apply for vercel for sure.

**Comment by chandansgowda** [comment]
We are not actually getting that sponsorship from appwrite. We will just use their BaaS for free since ours is an open source project. And coming to readme file, it still looks plain actually. Please look into it.

**Comment by ShivamMenda** [comment]
@chandansgowda yes will add the app screenshots. And add a few nice details to make it look good.

**Comment by chandansgowda** [comment]
Any updates @ShivamMenda ?

**Comment by ShivamMenda** [comment]
@chandansgowda adding app screenshots in a while. Will commit soon.

**Comment by ShivamMenda** [comment]
@chandansgowda Added the app screenshots and added emojis to make the readme look better. Can you check it out?

**Review by chandansgowda — CHANGES_REQUESTED** [review]
Great job till here @ShivamMenda 
Few changes:
1. Reduce the size of resonate logo in the top and add AOSSIE's logo also along with it in the same line
2. Use a different transparent logo for livekit
3. Appwrite recently redesigned their logo. Use it
4. Let livekit, vercel and appwrite come in the same line
5. Remove goals and app level design pattern section and add features section
6. Put the screenshots in a table with proper headings
7. Let maintainers section come before communication channels

**Comment by ShivamMenda** [comment]
@chandansgowda Sure will follow the list of changes👍

**Comment by chandansgowda** [comment]
Any update @ShivamMenda 
Actually this has to be done on priority since people will be looking forward to contribute in hacktoberfest.

**Comment by ShivamMenda** [comment]
@chandansgowda Doing it right now. Will commit asap

**Comment by ShivamMenda** [comment]
@chandansgowda made the requested changes. Please check.

**Review by chandansgowda — CHANGES_REQUESTED** [review]
1. Authentication is not a feature, please remove
2. Add Star the Repository statement in contributing section
3. Let repository links come before high level architecture
4. Remove screenshots showing minor features. Room screen and other major screenshots are missing

**Comment by ShivamMenda** [comment]
@chandansgowda all the changes are done. Did not get the pair chat screenshot. Not able to run it on the simulator. If you could provide the screenshot then I can include it.

**Comment by ShivamMenda** [comment]
@chandansgowda all changes done.

**Comment by chandansgowda** [comment]
Hey @ShivamMenda 
We migrated the node endpoints to appwrite cloud functions itself. Make necessary changes as soon as possible.

**Comment by ShivamMenda** [comment]
@chandansgowda what should I change with respect to the backend in the readme? Rest all requested changes are done

**Comment by chandansgowda** [comment]
@ShivamMenda 
Remove vercel deployment image 
Remove NodeJS references
Remove architecture image

We completely migrated nodejs api to appwrite cloud functions only. Make necessary changes

**Comment by ShivamMenda** [comment]
@chandansgowda Sure will do that

**Comment by ShivamMenda** [comment]
@chandansgowda Done with the requested changes.

**Pull request merged**
