### PR TITLE
Redirecting signedInUser to profile screen on app restart

### PR DESCRIPTION
**Pull request by chandansgowda**
@jddeep I have made use of the methods available from Auth0 and google_sign_in to check if a user is currently signed in. If yes, currently the user will be navigated to Profile Screen which can be changed to Home Screen once the home screen is ready. If not, the user will be in the login screen and has to either login/signup before proceeding further.

https://user-images.githubusercontent.com/41890434/230779141-94d42897-6841-4762-813d-1fb72115c7dd.mov

### CODE REVIEW

**Comment by jddeep** [comment]
@chandansgowda Did we manage to find a way to add the google signed in user to Auth0?

**Comment by chandansgowda** [comment]
@jddeep Once this PR gets merged, we will work on storing the user data to firebase. Regarding storing google user to Auth0, as far as my research goes, we just have one workaround here. It is to create an account on Auth0 as soon as the user signs in through google using their email address and a default strong password and use that account itself for the app. So, everytime the user signs in using google, we will use their Auth0 instance. The problem with this approach is that if someone comes to know about the default password, he can gain access to all the accounts using Google SignIn. So, what if we create a collection for users on Firebase and store their details over there?

**Comment by jddeep** [comment]
@chandansgowda I just spent some time on things. Let's go back Firebase Auth + Google Sign In for auth.

**Comment by chandansgowda** [comment]
Okay @jddeep 
Will work on that!

**Comment by chandansgowda** [comment]
@jddeep Please review #32

**Pull request closed without merging**
