### PR TITLE
feat: implemented dynamic theme switching functionality.

### PR DESCRIPTION
**Pull request by vrundraval24**
Added System Default, Light, and Dark themes. These themes are Persistent. Used GetX for storing theme data.

### CODE REVIEW

**Comment by chandansgowda** [comment]
@vrundraval24 It seems you have changed the background colour. It was a lighter before. Have not checked your code since I'm out. See if you have done that and change it back to the bg colour in AppColors.

**Comment by vrundraval24** [comment]
Yeah, I have changed it to pure black because pure black pixels consume very little battery. 

But no problem. I will change it to AppBgColor. Anything else you like to mention?

**Comment by vrundraval24** [comment]
Changed the background color to AppBgColor as you mentioned.

bg_change

**Comment by chandansgowda** [comment]
What about the bottom bar ??

**Comment by vrundraval24** [comment]
Bottom bar looks fine to me. Most apps have slight different colour of bottom bar than background colour. That's why I kept it black.
Shou

**Comment by chandansgowda** [comment]
@vrundraval24 I have attached the screenshot of the app as it looked before this change. You can observe that the appbar and bottom bar are in different colour but not actually the black you have used.

https://user-images.githubusercontent.com/41890434/246064681-16cfa072-af71-4e1f-97b8-2c429a875483.png

**Comment by vrundraval24** [comment]
Changed the Appbar and Bottom Navbar colors to the previous colors.
appbar_navbar

**Comment by vrundraval24** [comment]
@chandansgowda  Hey, is this proper? or need some more improvements?

meanwhile, can you assign me this issue #93 I would like to work on this. And I have worked on a similar kind of thing before as I mentioned there.

**Comment by vrundraval24** [comment]
@chandansgowda Hello, have you had a chance to review my code yet? If you have any feedback or think it's ready for merging, I'd appreciate your input. Thanks.

**Comment by vrundraval24** [comment]
[resonate screenshots Vrund.zip](https://github.com/AOSSIE-Org/Resonate/files/12838318/resonate.screenshots.Vrund.zip)

here are all the screenshots related to pair chat and audio room screens and one screen recording showcasing dynamic theme changes.

**Comment by chandansgowda** [comment]
Great job @vrundraval24 🚀

**Pull request merged**
