### PR TITLE
userName unavailable message showing

### LINKED ISSUE #388: Url Incorrect which is giving Error
### 🐛 Describe the bug

Screenshot_1730354995
While creating a new story Not able To fetch the Image and also in Create chapter as well

### PR DESCRIPTION
**Pull request by puneethkumar18**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please include screenshots below if applicable.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #388  (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by puneethkumar18** [comment]
Hi @Aarush-Acharya review my pr and let me know any corrections

**Comment by Aarush-Acharya** [comment]
Hey @puneethkumar18, you have not followed the commit culture as i informed earlier

**Comment by puneethkumar18** [comment]
@Aarush-Acharya okay do i need raise another one PR

**Comment by Aarush-Acharya** [comment]
Hey @puneethkumar18, just follow it in the upcoming commits no need to raise a new one

But I wish talk about the current methodology 

You are invoking a snackbar on every change, i initially thought you will show a cross or warning icon if  username is already taken in place of the current green tick 

what are your thoughts on it, which one would be better and also in any case make sure to use the debouncer i have used in the explore page search bar to not send a request to search on every character change rather let the user write it out and if we detect a gap of around 500 milliseconds then we send the request to fetch the search results. The logic is already there as a debouncer function i guess make sure to use that 

And yes let me know which one you feel is bettwe snackbar or a warning icon

**Comment by puneethkumar18** [comment]
@Aarush-Acharya my initial thought was showing an error icon , I had implemented that but when I asked some of my friends they prefer this if you want to change will do

**Comment by Aarush-Acharya** [comment]
If you prefer the snackbar lets keep it that way, please add the debouncer to it as i mentioned

**Comment by Aarush-Acharya** [comment]
please add debouncing to it and send a new commit

**Comment by puneethkumar18** [comment]
Okay @Aarush-Acharya I will do

**Comment by puneethkumar18** [comment]
@Aarush-Acharya  i have raised PR please check , let me know if  any corrections or changes required!

**Review by Aarush-Acharya — COMMENTED** [review]
Hey @puneethkumar18, good work implement the suggested change in the review 

Happy to see the improvement in commit culture

**Comment by puneethkumar18** [comment]
@Aarush-Acharya  i have made all changes you had told pls check and merge

**Comment by Aarush-Acharya** [comment]
hey @puneethkumar18, great work

**Pull request merged**
