### PR TITLE
ui: improved pair chat screen

### PR DESCRIPTION
**Pull request by ThienNg65**
#174

### CODE REVIEW

**Comment by chandansgowda** [comment]
Please share a scree recording of the same.

**Comment by chandansgowda** [comment]
Any update @ThienNg65 ?

**Comment by ThienNg65** [comment]
sorry for taking so long, i will take a screen shot for the UI right today

**Comment by ThienNg65** [comment]
@chandansgowda I make both User stay in a column to get rid of the blank space. Also, i create a container for them to hight light them to make the screen less plain.
Screenshot_1697441786

**Review by chandansgowda — APPROVED** [review]

**Pull request merged**
