### PR TITLE
 Handle null return value in Future<void> function

### LINKED ISSUE #292: Bug/null exception called when canceling room delete dialog
### 🐛 Describe the bug

 null return value in Future<void> function

### screenshot of the problem
 

Screenshot (1632)

### PR DESCRIPTION
**Pull request by kareemabdeen**
## Description
 This pull request resolves the issue where a null value was causing a subtype error in a function with a return type of Future<void>. By updating the return type to Future<dynamic>, the function can now handle null return values without any errors.

Fixes #292

## Type of change
 updating the return type to Future<dynamic>, the function can now handle null return values without any errors.

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue

## How Has This Been Tested?
- tested manually on my emulator

Please include screenshots below if applicable.
before bug fixes :
Screenshot (1632)

After
https://github.com/AOSSIE-Org/Resonate/assets/118139061/77f32e52-2b4e-498a-9bc5-6a4c1dc5edc7

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by kareemabdeen** [comment]
@chandansgowda , plz review changes, i would like to be helpfull

**Comment by chandansgowda** [comment]
@kareemabdeen  Please resolve conflicts

**Comment by kareemabdeen** [comment]
> @kareemabdeen Please resolve conflicts

done @chandansgowda

**Comment by kareemabdeen** [comment]
if there's any other problem please let me know @chandansgowda

**Comment by kareemabdeen** [comment]
if there's any other problem please let me know
@chandansgowda

**Review by chandansgowda — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
