### PR TITLE
fix: Resolve split-screen issue with SingleChildScrollView

### PR DESCRIPTION
**Pull request by arice77**
Fix : #152 

https://github.com/AOSSIE-Org/Resonate/assets/92450890/356dd091-1b97-4f7f-af30-43a60a83c337

### CODE REVIEW

**Comment by chandansgowda** [comment]
Hey @arice77 
How does it work in normal mode after this change ?

**Comment by arice77** [comment]
It works the same on the normal screen as well, the layout states the same only if the screen is small it gets scrollable instead of throwing he error "Bottom Overflowed".

**Comment by chandansgowda** [comment]
Okay @arice77 
Actually we are slightly redesigning this screen. Will merge this once that's done.

**Comment by arice77** [comment]
Sounds good  to me 👍

**Comment by 0xAdiyat** [comment]
Hey @arice77, I've been working on issue #150 and #155. You can find my contributions here. I've also made some changes based on @chandansgowda's feedback. I noticed that you've used a single child scrollview widget. It would be great if you could incorporate these changes into the updated codebase after #155 gets merged. Otherwise can be arrived.

**Comment by chandansgowda** [comment]
@arice77 Please resolve conflicts

**Pull request closed without merging**
