### PR TITLE
Fix textfield tag error 

### LINKED ISSUE #307: Bug : 'String' has no instance named 'isValidTag'
### 🐛 Describe the bug

When I try to add tags inside the 'create new room' page, it throws the error 'String' has no instance named 'isValidTag'.
WhatsApp Image 2024-03-21 at 11 42 56_fb6d87fc
Screenshot 2024-03-21 113558
May be fixed by #308

### PR DESCRIPTION
**Pull request by amanraval76593**
## Description

This PR solves the issue with textfield_tags where error "String' has no instance named 'isValidTag" was thrown after a tag was entered in the textfield.

Changes:-
Defines an inline function validateTag() within the scope of the validator.
Encapsulates the validation logic within this function.
Provides better encapsulation and organization of validation logic, enhancing readability and maintainability.
Fixes #307 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Test manually on physical device.
Before:
WhatsApp Image 2024-03-21 at 11 42 56_fb6d87fc
After
after

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Review by kareemabdeen — CHANGES_REQUESTED** [review]
I think it would be more beneficial for the overall structure and maintainability of the code if the validation logic was separated from the UI code.
For instance, you could place the `validateTag` function in the `CreateRoomController`

**Comment by amanraval76593** [comment]
> I think it would be more beneficial for the overall structure and maintainability of the code if the validation logic was separated from the UI code. For instance, you could place the `validateTag` function in the `CreateRoomController`

Yes you are right,i will do it. Thanks for the suggestion

**Comment by amanraval76593** [comment]
@chandansgowda please review the changes

**Comment by Aarush-Acharya** [comment]
Hey @amanraval76593  this is good to go, will merge once the PR previous to this one are merged
@kareemabdeen  Good work with the review thank you

**Pull request merged**
