### PR TITLE
fix: #247 added yaml file

### LINKED ISSUE #247: [Feature]: Add GitHub Action Workflow for Greeting Contributors
**Description:**
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

### Motivation, pitch

**Proposed Changes:**
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Expected Behavior:**
When contributors create new PRs or issues, the GitHub Action should automatically trigger and post a welcoming message, acknowledging their contributions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### PR DESCRIPTION
**Pull request by HimaTeju**
## Description

Implemented a GitHub Action to automatically greet new pull request (PR) and issue creators,

Fixes # #247 

## Type of change

Please delete options that are not relevant.

- [x] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please include screenshots below if applicable.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #247  (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by chandansgowda** [comment]
Hey @HimaTeju 
Please fill the PR checklist.

**Comment by HimaTeju** [comment]
@chandansgowda Donee!

**Comment by Aarush-Acharya** [comment]
@chandansgowda all good from my side

@HimaTeju good work

**Comment by HimaTeju** [comment]
@Aarush-Acharya Thank you for the kind words! I'm looking forward to contributing more!

**Comment by AyaNady17** [comment]
Great job @HimaTeju, I see it's good to merge 💯

**Comment by HimaTeju** [comment]
@AyaNady17 Thank You!

**Pull request merged**
