### PR TITLE
Create workflow for build and release

### LINKED ISSUE #319: Setup CI/CD for building the app and creating a release.
### 🚀 The feature

I propose a feature to include CI/CD for the main branch where anytime there's a code push, it builds the package, produces an APK as an artifact, and tags it with a release. 

### Motivation, pitch

This would introduce automation and a release pipeline and it would also help in tagging the releases, it would be a good progress check too, and we can always revert to the last stable build according to the version number in case of any failure.

### PR DESCRIPTION
**Pull request by ShivamMenda**
## Description

Created a CI Pipeline for build and release with Semantic versioning depending on the commit message

Fixes #319 

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This is yet to be tested because a PAT needs to be added to the project that can perform this workflow and then to be checked whether the release has been created properly with the workflow

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #319 
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by ShivamMenda** [comment]
@chandansgowda @Aarush-Acharya I've been trying to run this workflow but the app does not build correctly.
Screenshot 2024-05-25 at 1 21 17 AM

**Comment by Aarush-Acharya** [comment]
please do check if the current state of the app works on your local

**Comment by ShivamMenda** [comment]
Sure @Aarush-Acharya Will check

**Comment by ShivamMenda** [comment]
@Aarush-Acharya I think it's an issue with the code written for the health check, if you see in the logs, The health check part is where the build is breaking.

**Comment by Aarush-Acharya** [comment]
yes @ShivamMenda  it is from a PR recently merges for checking if the appwrite server is down if this is not working on CI CD flow i feel it would not work on local as well, just try building the current state of the app on your local, and see if it throws this error

If it does 
please try to resolve it 

else if it works 
check your dart version and flutter version and check the dart and flutter version in environment the build release is taking place

**Comment by ShivamMenda** [comment]
@Aarush-Acharya Will look into it, if it fails, I will open a PR to fix the Server check issue and then you can merge the CI CD PR.

**Comment by Aarush-Acharya** [comment]
@ShivamMenda understood

**Comment by Aarush-Acharya** [comment]
Hey @ShivamMenda let me know if any updates on solving the current error in the repo, please do have that one done ASAP as it might affect other contributors

**Comment by Aarush-Acharya** [comment]
Hey @ShivamMenda, the current error was solved we reverted changes, please do complete this asap and let me know

**Pull request closed without merging**
