### PR TITLE
Splash Screen along with App Logo Implemented

### PR DESCRIPTION
**Pull request by Aarush-Acharya**
closes https://github.com/AOSSIE-Org/Resonate/issues/61 and fixes https://github.com/AOSSIE-Org/Resonate/issues/57, fixed https://github.com/AOSSIE-Org/Resonate/issues/58, resolves https://github.com/AOSSIE-Org/Resonate/issues/65

Implemented the splash screen and app logo along with resolving issues while doing so 

migrated prebuilt splash screen from firebase core to appwrite core

### CODE REVIEW

**Review by chandansgowda — CHANGES_REQUESTED** [review]
Hey @Aarush-Acharya 
I'm getting an error while launching the app. I have attached a screenshot of the same.

Screenshot 2023-06-28 at 11 38 28 PM

**Comment by Aarush-Acharya** [comment]
I believed that the error is fixed now the only error left is that it is not connecting to the Appwrites project for that I believe I would need your project's ID (of the project that you created which has the right structure set up for the code written) else if that project ID is not to be revealed for its privacy and protection what we can do is I set up a proxy (false project trying to mimic the true projects structure for testing purposes) but then this projects ID would be pushed and that would not be convenient it would be like the testing project overtook the real one, so the first alternative is preferred

**Comment by Aarush-Acharya** [comment]
I looked into it and figured that it is because as the Appwrite isn't connecting to the project we are not navigating to any screen after using the animated splash screen it is displayed twice as we have used animated splash screen twice. This can be easily avoided if the Appwrite connects to the project for that I would need your Projects project ID (the project that you created and structured to match the current code logic that is written also your appwrite container )

**Comment by Aarush-Acharya** [comment]
Apologies got closed in an accident

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda I believe it is due to Appwrite not connecting to the project from my side trying to get it fixed

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda implemented a splash screen with Appwrite but did not do tunnelling or Digital ocean or Appwrite cloud go let me know what is to be done

**Comment by chandansgowda** [comment]
@Aarush-Acharya Lets go with local appwrite instance for now. I'll talk to @jddeep and will let you know what can be done.

**Review by chandansgowda — APPROVED** [review]

**Comment by Aarush-Acharya** [comment]
Okay thanks

**Comment by Aarush-Acharya** [comment]
hey @chandansgowda  please do test the app and do let me know of any issues

**Comment by chandansgowda** [comment]
@Aarush-Acharya I have tested it. No errors on my end.

**Comment by Aarush-Acharya** [comment]
Thank you for the review @chandansgowda

**Review by jddeep — APPROVED** [review]

**Pull request merged**
