### PR TITLE
feat: the discord icon redirects to discord page of aossie

### PR DESCRIPTION
**Pull request by ARYPROGRAMMER**
## Description

This PR improves the app by adding the feature to redirect user of AOSSIE discord page, they can discuss various topic there and learn more about this open source initiative

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This was tested on a real Android 14.0.1 Redmi Note 10 Pro device. Below is the video of the implementation: 

https://github.com/user-attachments/assets/48f064b7-602e-4717-a972-3cc12cdf49f7

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by ARYPROGRAMMER** [comment]
@Aarush-Acharya please review and merge this as well

**Comment by Aarush-Acharya** [comment]
Hey @ARYPROGRAMMER, I saw this and I was in discussion with Chandan about the telegram icon as if telegram exists for AOSSIE or not 


I would want you to look if AOSSIE has a telegram if you are able to find it then great lead to the telegram of AOSSIE from that button just like you are doing for discord 

IF you cannot find it then refactor the UI in a way that removes the telegram button and the UI still looks good

**Comment by ARYPROGRAMMER** [comment]
> Hey @ARYPROGRAMMER, I saw this and I was in discussion with Chandan about the telegram icon as if telegram exists for AOSSIE or not
> 
> I would want you to look if AOSSIE has a telegram if you are able to find it then great lead to the telegram of AOSSIE from that button just like you are doing for discord
> 
> IF you cannot find it then refactor the UI in a way that removes the telegram button and the UI still looks good

alright got it, currently at college would do it by 6 pm ist

**Comment by ARYPROGRAMMER** [comment]
> Hey @ARYPROGRAMMER, I saw this and I was in discussion with Chandan about the telegram icon as if telegram exists for AOSSIE or not
> 
> I would want you to look if AOSSIE has a telegram if you are able to find it then great lead to the telegram of AOSSIE from that button just like you are doing for discord
> 
> IF you cannot find it then refactor the UI in a way that removes the telegram button and the UI still looks good

I wasn't able to find telegram channel for the org, instead of making the ui more blank and pale, I added X(twitter) page link with updated logo

**Comment by ARYPROGRAMMER** [comment]
@Aarush-Acharya I hope this fixes the refracting problem and is a better alternative

**Comment by ARYPROGRAMMER** [comment]
@Aarush-Acharya any updates on this?

**Comment by AyaNady17** [comment]
> @Aarush-Acharya any updates on this?

Please provide a screen recording after the fix.

**Comment by ARYPROGRAMMER** [comment]
@AyaNady17 please find the video attached, this depicts the feature added:


https://github.com/user-attachments/assets/f9dd0b4b-c65a-4848-be2a-f78e3f3c2673

**Comment by ARYPROGRAMMER** [comment]
> > @Aarush-Acharya any updates on this?
> 
> Please provide a screen recording after the fix.

please review and merge

**Comment by AyaNady17** [comment]
Good job @ARYPROGRAMMER

**Pull request merged**
