### PR TITLE
fix: AuthenticationController-not-found

### LINKED ISSUE #194: AuthenticationController not found.
Bug: 
"AuthenticationController" not found. You need to call "Get.put(AuthenticationController())" or "Get.lazyPut(()=>AuthenticationController())"

Steps to reproduce the bug: 

1. There should be no rooms available or press the discussion tab and follow the below steps.
2. Press 'Add Icon' button
3. Press 'Pair Chat'
4. Press Cancel.

Fixes (I think can fix this issue):

1. Put AuthenticationController() in TabViewBinding() or make it 'permanent'.
2. Replace 'Get.offAllNamed()' with 'Get.back()' / Get.offUntil().

The first one will fix the issue but won't be able to maintain the state of the previous screen (Landing Screen), which the second fix can.  

@chandansgowda Can you please assign me this issue.

### PR DESCRIPTION
**Pull request by bhoomikshetty**
Fixes #194

### CODE REVIEW

**Review by chandansgowda — COMMENTED** [review]
@bhoomikshetty Are there no issues after replacing `Get.offAllNamed(AppRoutes.tabview)` with `Get.back()` ? I guess this makes the dependency injection a bit inconsistent. Please test all cases and let me know.

**Comment by bhoomikshetty** [comment]
> @bhoomikshetty Are there no issues after replacing `Get.offAllNamed(AppRoutes.tabview)` with `Get.back()` ? I guess this makes the dependency injection a bit inconsistent. Please test all cases and let me know.

Get.back() will cause issues, when we add few screens between the home screen and the chat pairing screen.

Get.offNamedUntil can fix issue.
We can pop the screen till 'tabview' from anywhere in the app.

**Comment by chandansgowda** [comment]
@bhoomikshetty Make that change and find out if all features work as expected.

**Review by chandansgowda — COMMENTED** [review]
Have you tested if there's no inconsistency after this change ?

**Comment by bhoomikshetty** [comment]
> Have you tested if there's no inconsistency after this change ?

Checked and couldn't find any issue

**Comment by Aarush-Acharya** [comment]
Hey @bhoomikshetty, thank you for your contributions, 

There are some conflicts please resolve them, will merge once resolved

**Pull request merged**
