### PR TITLE
Added image crop feature

### LINKED ISSUE #207: Feature to Crop image before setting it on the Profile Screen.
### 🚀 The feature

image

WhatsApp and Instagram provide the feature to Adjust or Crop the image before setting it to the profile screen. We can also add something like this in Resonate.

This feature needs to be added to ON BOARDING SCREEN and EDIT PROFILE SCREEN.

### Motivation, pitch

It enhances user experience.

@chandansgowda 
I want to work on this feature. Please assign me.

### PR DESCRIPTION
**Pull request by Aditya062003**
# Description

This pull request introduces a new feature to address issue #207. The added feature allows users to crop, rotate, and magnify images when setting their profile picture.

## Motivation and Context

The motivation behind this change is to enhance user experience and provide more flexibility when setting profile pictures. The ability to crop, rotate, and magnify images adds a layer of customization, allowing users to fine-tune their profile pictures to better suit their preferences.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

The following tests were conducted to verify the changes:

1. Uploaded an image for profile picture setting.
2. Used the cropping feature to select a specific area of the image.
3. Tested the rotation functionality to ensure it works as expected.
4. Verified the magnification option and its impact on the image.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] Closes #207 

## Screen Recording

https://drive.google.com/file/d/1MDh7KEAtFvI_ydpxOPrOSTmKVVKn3Y-_/view?usp=drivesdk

### CODE REVIEW

**Comment by chandansgowda** [comment]
Please add a screen recording of the same @Aditya062003

**Comment by Aditya062003** [comment]
> Please add a screen recording of the same @Aditya062003 

https://drive.google.com/file/d/1MDh7KEAtFvI_ydpxOPrOSTmKVVKn3Y-_/view?usp=drivesdk

Screen Recording showing full functionality of the feature, please let me know if there are any other requirements for testing.

**Comment by Aditya062003** [comment]
Hey @chandansgowda, I used the [Flutter image cropper](https://pub.dev/packages/image_cropper) package for this and reviewed all its parameters. Unfortunately, I couldn't find any options to change the bottom bar color. Please guide me on how to proceed next.

**Comment by chandansgowda** [comment]
@Aditya062003 Is there any other package that we can use ?

**Comment by Aditya062003** [comment]
Hey @chandansgowda , I tried a few other packages like `crop_image`, `crop_your_image`, and `custom_image_crop`, among others. However, they were not updated to the current versions. I could only find image crop features in the above three packages, not rotation and zoom functionalities. Unfortunately, all of them had the same issue of white bottom bar.

**Comment by chandansgowda** [comment]
Okayy @Aditya062003 
We can go with this one for now. Thanks for your contribution 🚀

**Pull request merged**
