### PR TITLE
Fixes #397: Implement Dynamic Theming for SVG Illustrations - Primary Color Adaptation

### LINKED ISSUE #397: Implement Dynamic Theming for SVG Illustrations - Primary Color Adaptation
### 🚀 The feature

Enable SVG illustrations within the app to adapt their primary color dynamically based on the theme, enhancing the app's visual coherence and user experience.

### Motivation, pitch

Currently, the SVG illustrations in the app have a static primary color, which may not always align with the active theme, especially if users switch between light and dark modes or customized themes. This feature would elevate the app’s aesthetic by allowing SVGs to seamlessly integrate with any chosen theme, improving consistency across UI elements.

### PR DESCRIPTION
**Pull request by xkaper001**
Fixes #397 

## Description

Replace raster images with dynamically colored SVGs for better scalability and theming in the application.
More Details here: https://github.com/AOSSIE-Org/Resonate/issues/397#issuecomment-2464922347

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #397 
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by xkaper001** [comment]
Hey @Aarush-Acharya Done :)

**Comment by xkaper001** [comment]
Hey @Aarush-Acharya, done :)

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001, I asked you to use the alternate no room UI the you pitched in the issues chat but here it is the initial one


please replace it with the alternate one

**Comment by xkaper001** [comment]
it already is the alternate one @Aarush-Acharya (a man with a big magnifying glass)

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001 got it my bad

**Pull request merged**
