### PR TITLE
Enhance]:Replace-deperacted-OnWillPopScope-with-PopScope 

### LINKED ISSUE #270: Deprecation Warning: Replace WillPopScope with PopScope
### 🐛 Describe the bug

The Flutter framework has deprecated the usage of WillPopScope constructor in favor of PopScope starting from version v3.12.0-1.0.pre. However, there are still instances of WillPopScope being used in the codebase of the project.

### PR DESCRIPTION
**Pull request by kareemabdeen**
## Description

Now, instead of using the deprecated OnWillPopScope, you can simply use PopScope to achieve the same functionality in a more efficient and future-proof way, 
also Refactored save changes Dialog as separated function in the app utils files to be separated from the ui code

Fixes #270

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?
with my emulator 

Please include screenshots below if applicable.
here is  how app functions after the changes had done 
https://github.com/AOSSIE-Org/Resonate/assets/118139061/ced336de-b05b-4af5-8386-18b1bd84f220

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by kareemabdeen** [comment]
@chandansgowda please review this pr and merge it ❤️

**Comment by kareemabdeen** [comment]
@chandansgowda if there's any problem on the branch please let me know

**Comment by Aarush-Acharya** [comment]
Hey @kareemabdeen, I had a question why have you taken the call back of onSave functionality as a parameter, is it for making it more reusable if so then why not take the callbacks of onDiscard as a parameter as well or well just take all the text strings and function call backs as parameters and making it into a general purpose pop up

So either make it static or make it entirely dynamic, or like just explain the case of keeping it sudo dynamic

**Comment by Aarush-Acharya** [comment]
Hey @kareemabdeen  this is already taken care of in #274

**Comment by vrundraval24** [comment]
Hey, @Aarush-Acharya 
It is a duplicate, but the original PR has some conflicts and the contributor is not responding so I am merging this.
I am removing the duplicate tag and also closing the original PR without merging.

Good work @kareemabdeen 🚀

**Pull request merged**
