### PR TITLE
Handle overflow exception from profile screen

### LINKED ISSUE #295: FIX: prevent overflow exception in Verify Email in Profile Screen
### 🐛 Describe the bug

overflow happened here  
Screenshot (1634)

### PR DESCRIPTION
**Pull request by kareemabdeen**
## Description

fix overflow when user click on verify email text in profile screen 

Fixes #295

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?
by my emulator 

Please include screenshots below if applicable.
before
 
Screenshot (1634)

after 

https://github.com/AOSSIE-Org/Resonate/assets/118139061/ef88a1e8-5764-45df-b98e-a4f5dcf07ade

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by kareemabdeen** [comment]
@chandansgowda please review and merge it ❤️

**Comment by kareemabdeen** [comment]
@chandansgowda please review and merge it ❤️

**Comment by kareemabdeen** [comment]
@chandansgowda if there's any problem on the branch please let me know

**Comment by Aarush-Acharya** [comment]
Hey @kareemabdeen  good work this PR is ready to merge, will merge after the ones prior to this are resolved

**Comment by vrundraval24** [comment]
Hey, @kareemabdeen Good work. We are merging this. 🚀

**Pull request merged**
