### PR TITLE
feat: added feature to change user email address

### LINKED ISSUE #320: Add a feature to Change User Email Address
### 🚀 The feature

Users will be able to change their email address. and the next time they login they will be able to use updated email address.

### Motivation, pitch

It is good to have this functionality when user is frequently using some other email and want to use that email in our app also. So they can manage things easily.

I am currently working on this issue. So, @chandansgowda please assign it to me.

### PR DESCRIPTION
**Pull request by vrundraval24**
## Description

Added functionality to change user email address. user will have to again verify email if they update their email address. email is changed in authentication and databases. and consistency is maintained.

Fixes #320 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I tested it in many ways and tried all possible cases. and everything works fine. and the screenshots and screen-recording of tests are added below.

## Screenshots
[Screenshots.zip](https://github.com/AOSSIE-Org/Resonate/files/14896261/Screenshots.zip)

## Screen Recording
https://github.com/AOSSIE-Org/Resonate/assets/141143426/57503cf4-55cd-4fd0-b13d-918cfae8e4cc

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] Tag the PR with the appropriate labels

### CODE REVIEW

**Review by chandansgowda — COMMENTED** [review]
@vrundraval24  The password field hint says that we need a password. Make it more clear. It should ideally be the current password of the user right ?

**Comment by Aarush-Acharya** [comment]
Hey @vrundraval24  Looks good, great work  🚀

Suggestions

- The email field hint says email please change that to "New Email" for making it more specific 
- For the Password field hint please make that to "Current Password"
- In the description text "For added security you must provide a password" I believe a password might create a confusion, make it to "For added security you must provide your account password"


Also I had a doubt how will people who have logged in using OAuth providers (Google, Github) avail this functionality 

Please do implement the suggested changes and push along with answering the doubt

**Comment by vrundraval24** [comment]
hey @Aarush-Acharya i made requested changes. please review it. and tell me if any changes required.

**Comment by Aarush-Acharya** [comment]
@vrundraval24  Looks good from my side

**Review by chandansgowda — APPROVED** [review]

**Pull request merged**
