### PR TITLE
Midterm evaluation

### PR DESCRIPTION
**Pull request by vrundraval24**
### Implemented these screens:

edit profile screen
email verification screen
forgot password screen
login screen
signup screen
onboarding screen
profile screen
settings screen
welcome screen
landing screens
user account screen
change email screen
delete account screen

### AND:

Implemented Dynamic Theme Switching Functionality.
Plus solved some minor bugs and issues related to the Password Strength Indicator, Pop Scope in the Edit Profile Screen, etc.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)

## Screenshots
[screenshots.zip](https://github.com/user-attachments/files/16115700/screenshots.zip)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by AyaNady17** [comment]
I see that everything is in excellent condition, Great job @vrundraval24

**Comment by chandansgowda** [comment]
@vrundraval24 Please resolve conflicts

**Comment by vrundraval24** [comment]
> @vrundraval24 Please resolve conflicts

Done ✅

@Aarush-Acharya @AyaNady17 @chandansgowda 
Please review this.

**Comment by Aarush-Acharya** [comment]
I have seen the code its good to go from side 
@chandansgowda

**Review by Aarush-Acharya — APPROVED** [review]
Hey chandan I have reviewed the changes they are all good to go

**Pull request merged**
