### PR TITLE
Filter rooms by Tags

### LINKED ISSUE #188: Filter rooms by tag in room list
This feature allows users to filter the rooms displayed on the home screen based on the tags assigned. 
@chandansgowda I would like to work on this feature.

### PR DESCRIPTION
**Pull request by ShivamMenda**
## Description
This pull request introduces a feature to filter rooms by the tags given by the user.

Fixes #188 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

https://github.com/AOSSIE-Org/Resonate/assets/74780977/4193ecc2-04b1-4498-a60d-3881e6c32852

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #188 
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by ShivamMenda** [comment]
@chandansgowda I have implemented the feature. Let me know if any other changes are required.

**Review by chandansgowda — CHANGES_REQUESTED** [review]
Great job till here @ShivamMenda 
I see that you are selecting two or three tags together and filtering. Make it as one tag. also improve the UI which comes below the app bar.

**Comment by ShivamMenda** [comment]
@chandansgowda selecting one tag which means, the user should be able to select only one tag at a time or there should be options of only one tag? Also regarding the UI where do you want me to keep the filter button?

**Comment by chandansgowda** [comment]
@ShivamMenda Please contact appwrite team and get an idea of an efficient database design for the same.

**Comment by ShivamMenda** [comment]
@chandansgowda Sire will discuss with them.

**Comment by chandansgowda** [comment]
Any updates @ShivamMenda ?

**Comment by ShivamMenda** [comment]
@chandansgowda dm'd a few people from the appwrite server. Did not get a reply. I'll put up a message in the flutter channel directly today. Will keep you posted.

**Comment by chandansgowda** [comment]
@ShivamMenda You can raise a ticket in their support channel.

**Comment by ShivamMenda** [comment]
@chandansgowda will do that.

**Comment by Aarush-Acharya** [comment]
Hey @ShivamMenda great work, cool new addition

Please do make the requested changes and we will merge it asap

**Comment by Aarush-Acharya** [comment]
Also @ShivamMenda  is the appwrite collection and system structure already implemented for this feature ??

**Comment by Aarush-Acharya** [comment]
Understood @ShivamMenda will look into it

**Comment by Aarush-Acharya** [comment]
Hey @ShivamMenda, please do let me know what do you propose as an alteration of the current room db structure for it to work

**Pull request closed without merging**
