### PR TITLE
Fix: Removed logo, made the login and signup screen responsive for small screen devices

### LINKED ISSUE #151: Issue - Not Displaying the Entire Validation Message for TextFormField on Signup Screen in small screen devices(eg. iPhone SE 3rd Gen)
**Expected Behavior:** The validation message for the TextFormField should be fully visible and readable, even if it spans multiple lines.

***Steps to Reproduce***
- Navigate to the Signup screen of the application.
- Attempt to submit an invalid password (e.g., less than 6 characters, missing lowercase/uppercase characters, missing numeric characters).
- Observe the validation message that appears below the password TextFormField.

image

> This issue is affecting the Signup screen specifically.
> Other TextFormField components in the application may also exhibit similar behavior.

I have already implemented the solution in my codebase. It would be great if I'm assigned to it.

### PR DESCRIPTION
**Pull request by 0xAdiyat**
- [x] Ensure full visibility of validation message for password field
- [x] Implement text wrapping for long validation messages
- [x] Removed logo
- [x] made the text "Back" and "Resonate" bold to give it a little bit of detail

Closes #150, Closes #151

### CODE REVIEW

**Comment by 0xAdiyat** [comment]
This is how it looks right now. And yeah I have made the text "Back" and "Resonate" bold to give it a little bit of detail. Is it all gd now? @chandansgowda 

image


image


image


image

**Comment by chandansgowda** [comment]
Now we'll have to tweak the UI a bit to make it not look empty on the top. Please take inspiration from designs on dribble or existing applications and edit it a bit.

**Comment by 0xAdiyat** [comment]
> Now we'll have to tweak the UI a bit to make it not look empty on the top. Please take inspiration from designs on dribble or existing applications and edit it a bit.

I did thought of aligning the text at left making the second text larger and first text smaller to make it look gd... sounds gd?

**Comment by 0xAdiyat** [comment]
@chandansgowda is it gd now? 

image


image

**Comment by 0xAdiyat** [comment]
And here is login screen

image
image

**Comment by chandansgowda** [comment]
Can you try out different designs? This doesnt hold good with our design and theme.

**Comment by chandansgowda** [comment]
Please resolve conflicts and also coordinate with @AKASHANGADII to get the top part of the screens right.

**Comment by 0xAdiyat** [comment]
@chandansgowda i have resolved the errors... now you can marge it. (1)
image

**Comment by chandansgowda** [comment]
Great job @0xAdiyat 🚀

**Pull request merged**
