### PR TITLE
[BugFix] Fix for Null Check Operator Used on a Null Value Exception in UiSizes Class

### LINKED ISSUE #288: BUG: _TypeError (Null check operator used on a null value)
### 🐛 Describe the bug

The following exception was thrown when launching the app on device using API 34:
 **_TypeError (Null check operator used on a null value)**
```
═══════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building MyApp(dirty):
Null check operator used on a null value

The relevant error-causing widget was:
    MyApp MyApp:file:///E:/FlutterProjects/Resonate/lib/main.dart:33:16

When the exception was thrown, this was the stack:
#0      GetNavigation.window (package:get/get_navigation/src/extension_navigation.dart:1169:44)
extension_navigation.dart:1169
#1      GetNavigation.size (package:get/get_navigation/src/extension_navigation.dart:1176:20)
extension_navigation.dart:1176
#2      GetNavigation.width (package:get/get_navigation/src/extension_navigation.dart:1179:23)
extension_navigation.dart:1179
#3      UiSizes.size_56 (package:resonate/utils/ui_sizes.dart:119:39)
ui_sizes.dart:119
#4      UiSizes.size_56 (package:resonate/utils/ui_sizes.dart)
#5      Themes.lightTheme (package:resonate/themes/themes.dart:25:30)
themes.dart:25
#6      Themes.lightTheme (package:resonate/themes/themes.dart)
#7      MyApp.build (package:resonate/main.dart:51:21)
main.dart:51
#8      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550:49)
framework.dart:5550
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
framework.dart:5480
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
framework.dart:5196
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462:5)
framework.dart:5462
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
framework.dart:5456
...     Normal element mounting (27 frames)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
framework.dart:4335
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
framework.dart:3846
#41     _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:291:16)
view.dart:291
#42     _RawViewElement.mount (package:flutter/src/widgets/view.dart:314:5)
view.dart:314
...     Normal element mounting (7 frames)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
framework.dart:4335
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
framework.dart:3846
#51     RootElement._rebuild (package:flutter/src/widgets/binding.dart:1354:16)
binding.dart:1354
#52     RootElement.mount (package:flutter/src/widgets/binding.dart:1323:5)
binding.dart:1323
#53     RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1276:18)
binding.dart:1276
#54     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2844:19)
framework.dart:2844
#55     RootWidget.attach (package:flutter/src/widgets/binding.dart:1275:13)
binding.dart:1275
#56     WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1088:27)
binding.dart:1088
#57     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1070:5)
binding.dart:1070
#58     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1056:7)
binding.dart:1056
#62     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)

```

Here is the screenshot:

image

### PR DESCRIPTION
**Pull request by AyaNady17**
## Description

This PR addresses the issue where a `Null check operator used on a null value` exception is thrown when trying to access `Get.width` and `Get.height` in the `UiSizes` class before the `BuildContext` is available.

The solution involves refactoring the `UiSizes` class to use `late` keyword for the size variables and initializing them in a new `init` method which is called after the `BuildContext` is available. 'MediaQuery' is used to get the screen sizes.
Fixes #288 

## Changes:
1. Refactored the `UiSizes` class to use `late` keyword for the size variables.
2.  Added an `init` method in `UiSizes` class to initialize the size variables using `MediaQuery`.
3. Called `UiSizes.init()` in the `build` method of the main widget.

## How Has This Been Tested?

1. Run the app to ensure it loads without throwing the `Null check operator used on a null value` exception.
2. Check various parts of the app to ensure that the sizes are being applied correctly.

 

https://github.com/AOSSIE-Org/Resonate/assets/144162711/57346fcb-7e5e-4e6b-9fd5-ed527b031c0a
Screenshot (182)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by AyaNady17** [comment]
please let me know your feedback. @chandansgowda

**Comment by chandansgowda** [comment]
Great job @AyaNady17 
Please add a screen recording showing that the app works.

**Comment by chandansgowda** [comment]
Also, have you upgraded flutter to latest version ?

**Comment by AyaNady17** [comment]
> Great job @AyaNady17 Please add a screen recording showing that the app works.
 done @chandansgowda

**Comment by AyaNady17** [comment]
> Also, have you upgraded flutter to latest version ?

until now I'm working on the Flutter 3.16.5 version.
 should i upgrade to the latest version before merging the changes?
 @chandansgowda

**Comment by bhawesh2002** [comment]
**Question:** Instead of using late keyword can we directly use `MediaQuery` to get the screen size?
I did the same thing in other one of my flutter app and it still worked fine. If this is possible we can avoid use of `late` keyword.

**Comment by AyaNady17** [comment]
> **Question:** Instead of using `late` keyword can we directly use `MediaQuery` to get the screen size? I did the same thing in other one of my flutter app and it still worked fine. If this is possible we can avoid use of `late` keyword.

if we declared sizes without using the late keyword, we must initialize it with a specific value. Otherwise, we’ll encounter an error. In our case, when trying to get screen sizes using MediaQuery, the context isn’t fully available during object initialization. So, using late ensures that we can safely access the context later, once it’s fully initialized.
@bhawesh2002

**Comment by chandansgowda** [comment]
Gr

> > Also, have you upgraded flutter to latest version ?
> 
> until now I'm working on the Flutter 3.16.5 version. should i upgrade to the latest version before merging the changes? @chandansgowda

Let's upgrade before merging this PR.

**Comment by AyaNady17** [comment]
> Great Job @AyaNady17
> 
> > > Also, have you upgraded flutter to latest version ?
> > 
> > 
> > until now I'm working on the Flutter 3.16.5 version. should i upgrade to the latest version before merging the changes? @chandansgowda
> 
> Let's upgrade before merging this PR.

done, upgraded to the latest stable version. 
@chandansgowda

**Comment by AyaNady17** [comment]
> > Great Job @AyaNady17
> > > > Also, have you upgraded flutter to latest version ?
> > > 
> > > 
> > > until now I'm working on the Flutter 3.16.5 version. should i upgrade to the latest version before merging the changes? @chandansgowda
> > 
> > 
> > Let's upgrade before merging this PR.
> 
> done, upgraded to the latest stable version with no errors. @chandansgowda

**Comment by AyaNady17** [comment]
Due to the upgrade one of the packages (text field tags) updated to latest version where one of its attributes have changed and I refactored it to fit with the update so there's some changes in ui file and pubspec.Yaml but now everything works will with the latest versions

**Comment by chandansgowda** [comment]
Thanks for contributing @AyaNady17

**Pull request merged**
