### PR TITLE
Migrate to declarative plugin declaration from imperative plugin declaration 

### LINKED ISSUE #289: BUG: You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method
### 🐛 Describe the bug

The application is not getting built because gradle plugins were applied using the imperative method which is deprecated.
The error:
```
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Mig rate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply
Warning: The plugin url_launcher_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration. One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to E:\FlutterProjects\Resonate\android\app\build.gradle: android {
compileSdkVersion 34
```
The Screenshot of the error:
Screenshot (66)

### PR DESCRIPTION
**Pull request by bhawesh2002**
## Description

Migrate to gradle's declarative plugin declaration from imperative plugin declaration as refrenced in
[Deprecated imperative apply of Flutter's Gradle plugins](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)

Fixes 
#289 : BUG: You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method
## Type of change

Modify :

- **android\build.gradle**,
- **android\app\build.gradle** 
- **android\settings.gradle**

to migrate to gradle's declarative plugin declaration

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

1. Tested on flutter version: image
2. Tested on android emulator API 34, API 33 and API 31. 

**No errors were encountered. Please include screenshots below if applicable.**

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] closes #289 (Replace xxxx with the GitHub issue number)
- [x] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by bhawesh2002** [comment]
The Exception: _TypeError (Null check operator used on a null value)
**_is yet to be fixed._**
The problem is with 
`static double size_56 = 0.068 * Get.width + 0.034 * Get.height;` 
from **lib\utils\ui_sizes.dart**

**Comment by Aarush-Acharya** [comment]
Hey @bhawesh2002 this PR is good to merge, will merge once the PR previous to this are resolved

**Comment by bhawesh2002** [comment]
Yes, I have resolved the issues and it is good to merge

**Comment by vrundraval24** [comment]
Good work @bhawesh2002 🚀

**Pull request merged**
