### PR TITLE
Fix bottom overflowed error on login screen, Fix the Splash radius of buttons on profile page and minor changes

### PR DESCRIPTION
**Pull request by bhawesh2002**
## Major fixes:
1. Fix Splash radius of buttons on profile page
2. Fix the RenderFlex overflowed error of discussion tile
3. Fix bottom overflowed error on login screen

## Minor Changes
1. Remove unused imports from the code files inside lib dir to improve performance
2. Rename identifiers according to lowerCamelCase naming convenction
4. Add const modifier wherever possible to improve performance
5. Use debugPrint instead of print
6. Remove unnessary string interpolations

## Major:
1. [The splash radius of buttons on the profile page exceeds the border #284](https://github.com/AOSSIE-Org/Resonate/issues/284)
2. [Bug:- Bottom overflowed error on login screen #287](https://github.com/AOSSIE-Org/Resonate/issues/287)

## Minor: 
1. [Remove unused import #248](https://github.com/AOSSIE-Org/Resonate/issues/248)
2. [use lowerCamelCase identifier names #267](https://github.com/AOSSIE-Org/Resonate/issues/267)
3. [Clearing up Unused Imports & Improving Performance #158](https://github.com/AOSSIE-Org/Resonate/issues/158)

## Major
1. Make use of Material widget to wrap InkWell and specify border radius to avoid the overflow of splash when button is tapped.
_**Before**:_ 
Screenshot_1709188487
_**After:**_
Screenshot_1709190839

2. Change the layout of login screen widgets to account for a more responsive design.
_**Before**_
Screenshot_20240301-102153
_**After:**_
Screenshot_20240301-112133

## Minor
1. Remove unused imports to keep the code clean and improve performance
2. Rename identifiers as specified in [non_constant_identifier_names](https://dart.dev/tools/linter-rules/non_constant_identifier_names)
4. Add const modifers to improve performance which notifies dart that the widgets with const modifiers are compile-time constants.
5. Use debugPrint instead of print as specified in [avoid print calls in production code](https://dart.dev/tools/linter-rules/avoid_print).
6. Remove unnessary string interpolations as specified in [unnecessary_string_interpolations](https://dart.dev/tools/linter-rules/unnecessary_string_interpolations)

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)

## How Has This Been Tested?
Tested manually on android emulator(API 31 and API 34) and Moto g40 fusion. No errors were encountered after the changes were made.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by bhawesh2002** [comment]
I have remove unused imports and made some refactorings to the code files.

**Comment by bhawesh2002** [comment]
I have renamed identifiers according to lowerCamelCase naming convenction

**Comment by bhawesh2002** [comment]
I have added const modifier wherever possible to improve performance as specified in [prefer_const_constructors](https://dart.dev/tools/linter-rules/prefer_const_constructors)

**Review by chandansgowda — COMMENTED** [review]
Have you tested the whole app after these changes ?

**Comment by bhawesh2002** [comment]
> Have you tested the whole app after these changes ?

Yes. I did test the changes on API 34 emulator and physical device running API 32 as well and everything worked fine.

**Comment by bhawesh2002** [comment]
@chandansgowda 
**Update:** I made the changes to UiSizes refering to #291 and tested the app. The app is working fine and throws no errors.

**Pull request closed without merging**
