### PR TITLE
feat: Assigning moderators for the room

### LINKED ISSUE #91: Feature for admins to assign moderators for the room

### PR DESCRIPTION
**Pull request by ShamanthOP**
Closes #91 

Added a feature for Room admin to assign Moderators for the room.

Moderator actions:

- Make participants Speaker if they request to speak.
- Revert participants back to Listeners.
- Kick the participants from the room.

Room admin actions:

- All the actions that Moderators can do.
- Make participants Moderator.
- Remove the Moderator role.

### CODE REVIEW

**Comment by chandansgowda** [comment]
Hey @ShamanthOP 
Please add a screen recording demonstrating the feature. Also, can you list down the testcases you have tested ?

**Comment by ShamanthOP** [comment]
[Screen Recording](https://clipchamp.com/watch/wr8KM4ErC6V)

Tested cases:
- Admin assigning Mods.
- Admin removing Mods.
- Mods promoting participants to Speakers.
- Mods demoting participants to Listeners.
- Mods kicking out participants from the room.
- Mod-to-Mod: Same role no action allowed.

**Comment by chandansgowda** [comment]
Hey @ShamanthOP 
I have merged your PR regarding centralised appwrite service. Pull it to this branch and check if it works as expected. Just to confirm that merge doesn't break thinks again.

**Comment by ShamanthOP** [comment]
@chandansgowda Rechecked the flow once more. Everything works fine.

**Comment by chandansgowda** [comment]
Great job @ShamanthOP 🚀

**Pull request merged**
