### PR TITLE
Fix: Set clip behavior to antiAlias in CustomCard widget to fix splash overflow

### LINKED ISSUE #284: The splash radius of buttons on the profile page exceeds the border
### 🐛 Describe the bug

When the button on the profile page is clicked the splash goes beyond the borders of button

Screenshot_1709188487

### PR DESCRIPTION
**Pull request by bhawesh2002**
## Description

**Problem:** 
When tiles on profile page are tapped the spalsh exceedes the visible boundry of the tiles.

**Preview of the problem:**
image

**Reason:**
CustomCard widget(from custom_card.dart) is used for creation of tiles on ProfileScreen(from profile_screen.dart).

So when the user taps the tiles the splash generated by the Inkwell of the CustomCard widget excceedes the visible boundries of the CustomCard causing overflow.

**Fix:**
 Fixed splash overflow issue by setting clipBehaviour to clip.antiAlias in Card widget of CustomCard widget.

## Fixes 
#284: [The splash radius of buttons on the profile page exceeds the border](https://github.com/AOSSIE-Org/Resonate/issues/284)  

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)

## How Has This Been Tested?

The changes have been tested on android emulator(API 33 and 32) and do not cause any additional issues.

**Screenshot after Fix**

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by AyaNady17** [comment]
Good Work @bhawesh2002 🚀

This is good to merge will merge after the previously scheduled PR's are merged

**Comment by vrundraval24** [comment]
Hey, @bhawesh2002 please resolve the merge conflicts. Then we will merge this PR.

**Comment by bhawesh2002** [comment]
@vrundraval24 I have resolved the merge conflicts

**Comment by vrundraval24** [comment]
Great job @bhawesh2002 🚀
We are merging this branch, keep contributing.

**Pull request merged**
