### PR TITLE
fix: Null check Error on Discussion page

### PR DESCRIPTION
**Pull request by SharmaDhruv2511**
## Description

There is error of null check on discussions page and that's why discussion page is not loading. This issue resolve that error

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
#220 

## Type of change
Bug

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please include screenshots below if applicable.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by SharmaDhruv2511** [comment]
Done with the checklist @chandansgowda

**Comment by chandansgowda** [comment]
We will have to wait for @Aarush-Acharya to review the PR since he was the one who worked on the Discussion feature. Until then please add a screen recording showing the fix.

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda apologies for the inactivity

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda  this is just ensuring null safety there is not any other change a couple of null checks, and it will safegaurd from null errors so its safe from my side thanks

**Pull request merged**
