### PR TITLE
Fixes #358: Update and compress image assets

### LINKED ISSUE #358: Picture Image resolution too high
### 🐛 Describe the bug

The picture being used as an emoji for no connection dialog and no room dialog is of 1800 x 1800 resolution which is very high. The resolution makes the current size of the Images to be around 4 mb each which is too much 

Scale the images down to 10Kb. If the image resolution falls below acceptance once you reach this image size then just simply replace it with a Text Emoji but the size should be around 10Kb

### PR DESCRIPTION
**Pull request by xkaper001**
## Description

This pull request replaces existing images with compressed versions and refactors image references throughout the application. The changes enhance performance by reducing asset sizes and improving code maintainability through the use of a centralized image asset management system. Additionally, some dependencies have been updated to their latest versions.

Fixes #358

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

I've tested the updated code on a physical device using flutter `v3.24.3` 

Please include screenshots below if applicable.
 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001, good work ensuring the code quality in other places as well where it involved image paths 


There are some conflicts between the dev branch and your branch that you are merging please resolve the conflicts carefully and push again

**Comment by xkaper001** [comment]
Resolved @Aarush-Acharya :)

**Comment by Aarush-Acharya** [comment]
hey @xkaper001, you have deleted some of the new changes this will cause regression in the codebase, i cannot allow a regression. please solve it correctly

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001, do not give up 

You were going good, just the one bad merge in the end took it down the road 

I am here for help you can discord dm me let me know if you need help

**Comment by xkaper001** [comment]
yeah 🥲 I'm on my way to make another pr (clean this time).

**Pull request closed without merging**
