### PR TITLE
docs: description for store listing

### LINKED ISSUE #109: App Description for Store Listing
Write an engaging and informative app description for the store listing on both Google Play Store and Apple App Store. The app description should highlight the unique features, functionalities, and benefits of Resonate, making it appealing to potential users.

### PR DESCRIPTION
**Pull request by NishchayShakya1**
## Description

Added the App Description as mentioned.

## Type of change

- [x] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] closes #109 
- [x] `documentation` `good first issue` `hacktoberfest`

### CODE REVIEW

**Review by chandansgowda — COMMENTED** [review]
Looks good @NishchayShakya1 
Why do we have ** on start and end of lines? Also, improve the readability as well as app store optimization.

**Comment by NishchayShakya1** [comment]
> Looks good @NishchayShakya1 Why do we have ** on start and end of lines? Also, improve the readability as well as app store optimization.

** makes the phrase bold. Okay, I will try to improve the improve the readability as well as app store optimization.

**Review by NishchayShakya1 — COMMENTED** [review]
Optimized the Description

**Comment by NishchayShakya1** [comment]
Fixed!
I have pushed another commit, please check it.

**Comment by chandansgowda** [comment]
Looks good @NishchayShakya1 
Thanks for contributing 🙌

**Pull request merged**
