### PR TITLE
Implemented CreateRoom, Rooms and SingleRoom Controllers

### PR DESCRIPTION
**Pull request by chandansgowda**
This PR includes the following additions:
1. CreateRoom Controller to validate create room form and call createRoom method
2. Rooms Controller to get all active rooms from Appwrite Database
3. Single Room Controller to open a realtime subscription for room management

### CODE REVIEW

**Comment by chandansgowda** [comment]
This PR was closed since there was an issue while resolving merge conflicts.

**Comment by Aarush-Acharya** [comment]
@chandansgowda sincere apologies if it was due to my merge wasn't aware that you were also working on the UI part

**Comment by chandansgowda** [comment]
@chandansgowda Its okayy. As far as I know it was a server error from Github. I had resolved the conflicts and pushed the commit to controllers branch but it was not getting updated in the PR.

**Comment by Aarush-Acharya** [comment]
Okay got it alright

**Pull request closed without merging**
