### PR TITLE
[FEATURE] Implement Dynamic Theming for User-Selected App Color

### LINKED ISSUE #281: Feature: Implement Dynamic Theming with User-Selected App Color
### 🚀 The feature

Introducing dynamic theming to allow users to select the app color presents an exciting opportunity for enhancing user experience and personalization. 

### Motivation, pitch

 Users will be empowered to personalize the app to suit their preferences, enhancing engagement and satisfaction.

### PR DESCRIPTION
**Pull request by AyaNady17**
## Description

This pull request introduces a dynamic theming feature that allows users to personalize the app's color scheme according to their preferences.
Fixes #281 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
 

## How Has This Been Tested?
tested manually 

 
https://github.com/AOSSIE-Org/Resonate/assets/144162711/b03fa16b-6013-460a-aac6-2e717e309a6b

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

### CODE REVIEW

**Comment by AyaNady17** [comment]
please review @chandansgowda

**Review by chandansgowda — COMMENTED** [review]
Do we have to put the theme controller in each screen and controller? There should be cleaner alternatives for this.

**Comment by AyaNady17** [comment]
Thanks for the feedback. I've corrected the redundancy by using Get.find() to retrieve the theme controller instance, simplifying the code. in the future, I'll ensure to follow cleaner alternatives like this.
@chandansgowda

**Comment by AyaNady17** [comment]
there's any other problem? @chandansgowda

**Comment by AyaNady17** [comment]
I've solved the conflict @chandansgowda

**Review by chandansgowda — APPROVED** [review]
Great Job @AyaNady17

**Pull request merged**
